# _______       _____      ______ _____________               ________                        ______
# __  __ \___  ____(_)________  /___  ___/__  /_________________  ___/__________ ________________  /_
# _  / / /  / / /_  /_  ___/_  //_/____ \__  __ \  __ \__  __ \____ \_  _ \  __ `/_  ___/  ___/_  __ \
# / /_/ // /_/ /_  / / /__ _  ,<  ____/ /_  / / / /_/ /_  /_/ /___/ //  __/ /_/ /_  /   / /__ _  / / /
# \___\_\\__,_/ /_/  \___/ /_/|_| /____/ /_/ /_/\____/_  .___//____/ \___/\__,_/ /_/    \___/ /_/ /_/
#                                                     /_/
#
# QuickShopSearch - Developed by BlvckBytes <blvckbytes@gmail.com>
# Repository - https://github.com/BlvckBytes/QuickShopSearch
# ASCII-Art - https://patorjk.com/software/taag/#p=display&f=Speed

# - current_page: Integer
# - number_pages: Integer
resultDisplay:
  title$: '"&8Shop Search &e" & current_page & "&8/&e" & number_pages'
  # https://github.com/BlvckBytes/BukkitEvaluable#itemstack-section
  previousPage:
    type: PLAYER_HEAD
    textures$: 'lut["textures"][if current_page > 1 then "ARROW_LEFT" else "ARROW_LEFT_RED"]'
    name$: '"&8» " & (if current_page > 1 then "&6Previous Page" else "&cNo Previous Page") & " &8«"'
    lore$:
      - '" "'
      - '"&8&m                                                  "'
      - '"&8➥ &eLeft-Click &7Navigate to previous page"'
      - '"&8➥ &eRight-Click &7Jump to very first page"'
      - '"&8&m                                                  "'
  # https://github.com/BlvckBytes/BukkitEvaluable#itemstack-section
  nextPage:
    type: PLAYER_HEAD
    textures$: 'lut["textures"][if current_page < number_pages then "ARROW_RIGHT" else "ARROW_RIGHT_RED"]'
    name$: '"&8» " & (if current_page < number_pages then "&6Next Page" else "&cNo Next Page") & " &8«"'
    lore$:
      - '" "'
      - '"&8&m                                                  "'
      - '"&8➥ &eLeft-Click &7Navigate to next page"'
      - '"&8➥ &eRight-Click &7Jump to very last page"'
      - '"&8&m                                                  "'
  # - owner: String
  # - price: Double
  # - currency: String?
  # - remaining_stock: Integer
  # - remaining_space: Integer
  # - is_selling: Boolean
  # - is_buying: Boolean
  # - is_unlimited: Boolean
  # - loc_world: String?
  # - loc_x: Integer
  # - loc_y: Integer
  # - loc_z: Integer
  # - distance: Integer
  # https://github.com/BlvckBytes/BukkitEvaluable#itemstack-section
  representativePatch:
    lore$:
      - '" "'
      - '"&8&m                                                  "'
      - '"&8♦ &7Owner: &e" & owner'
      - '"&8♦ &7Price: &e" & price & " " & (currency ?? "")'
      - '"&8♦ &7Space: &e" & remaining_space'
      - '"&8♦ &7Stock: &e" & remaining_stock'
      - '"&8♦ &7Coordinates: &e" & loc_x & "&7, &e" & loc_y & "&7, &e" & loc_z'
      - '"&8♦ &7Distance: " & if distance < 0 then "&cDifferent World" else "&e" & distance & " Blocks"'
      - |
        color_code = (flag, value) => (if flag then "&a" else "&c") & value
        "&8♦ &7Features: "
          & color_code(is_buying, "buying")
          & "&7, " & color_code(is_selling, "selling")
          & "&7, " & color_code(is_unlimited, "unlimited")
      - '"&8&m                                                  "'
      - '"&8➥ &eLeft-Click &7Teleport to the shop"'
      - '"&8➥ &eRight-Click &7Open preview"'
      - '"&8&m                                                  "'
  # - sorting_selections: Iterable<SortingCriterionSelection>
  # - selected_index: Integer
  # https://github.com/BlvckBytes/BukkitEvaluable#itemstack-section
  sorting:
    type: COMPARATOR
    name: "&8» &6Sorting &8«"
    lore$:
      - '" "'
      - '"&8&m                                                  "'
      - |
        map(sorting_selections, (entry, entry_index) => (
          (if entry_index == selected_index then "&e" else "&8") & "➥ "
          & (lut["sortingSelectionStyle"][str(entry.selection)] ?? "Style Missing")
          & (lut["sortingCriteria"][str(entry.criterion)] ?? "Criteria Missing")
        ))
      - '"&8&m                                                  "'
      - '"&8➥ &eLeft-Click &7Cycle through criteria"'
      - '"&8➥ &eRight-Click &7Toggle order"'
      - '"&8➥ &eDrop &7Move criterion down"'
      - '"&8&m                                                  "'
  # - filtering_selections: Map<ShopFilteringCriteria, PredicateSelection>
  # - selected_criteria: ShopFilteringCriteria
  # https://github.com/BlvckBytes/BukkitEvaluable#itemstack-section
  filtering:
    type: HOPPER
    name: "&8» &6Filtering &8«"
    lore$:
      - '" "'
      - '"&8&m                                                  "'
      - |
        map(filtering_selections, (entry) => (
          (if key(entry) == selected_criteria then "&e" else "&8") & "➥ "
          & (lut["predicateSelectionStyle"][str(value(entry))] ?? "Style Missing")
          & (lut["filteringCriteria"][str(key(entry))] ?? "Criteria Missing")
        ))
      - '"&8&m                                                  "'
      - '"&8➥ &eLeft-Click &7Cycle through criteria"'
      - '"&8➥ &eRight-Click &7Toggle state"'
      - '"&8&m                                                  "'
  # https://github.com/BlvckBytes/BukkitEvaluable#itemstack-section
  filler:
    type: BLACK_STAINED_GLASS_PANE
    name: " "

playerMessages:
  emptyPredicate$: 'lut["MESSAGE_PREFIX"] & "&cPlease provide a non-empty predicate."'
  noMatches$: 'lut["MESSAGE_PREFIX"] & "&cYour query resulted in zero matches."'
  # - owner: String
  # - price: Double
  # - currency: String?
  # - remaining_stock: Integer
  # - remaining_space: Integer
  # - is_selling: Boolean
  # - is_buying: Boolean
  # - is_unlimited: Boolean
  # - loc_world: String?
  # - loc_x: Integer
  # - loc_y: Integer
  # - loc_z: Integer
  # - distance: Integer
  beforeTeleporting$: 'lut["MESSAGE_PREFIX"] & "&7Teleporting to the Shop of &e" & owner & " &7at &e" & loc_x & "&7, &e" & loc_y & "&7, &e" & loc_z & "&7."'
  # - number_shops: Integer
  # - predicate: String
  beforeQuerying$: 'lut["MESSAGE_PREFIX"] & "&7Querying &e" & number_shops & " Shops &7for &e" & predicate & "&7..."'
  # - number_shops: Integer
  queryingAllShops$: 'lut["MESSAGE_PREFIX"] & "&7Querying &eall &7(&e" & number_shops & "&7) Shops..."'
  # - label: String
  # - languages: Collection<String>
  usageQsslCommandLanguage$: 'lut["MESSAGE_PREFIX"] & "&7Usage: /" & label & " <" & iter_cat(languages, (language) => "&e" & language, "&7, ") & "&7> [Predicate]"'
  # - user_input: String
  unknownLanguageActionBar$: '"&cUnknown language: &4" & user_input & "&c."'
  pluginReloadedSuccess$: 'lut["MESSAGE_PREFIX"] & "&7The plugin has been &ereloaded &7successfully."'
  pluginReloadedError$: 'lut["MESSAGE_PREFIX"] & "&cAn error occurred while trying to reload the plugin. Check the console!"'
  # - exception_message: String
  predicateParseError$: 'lut["MESSAGE_PREFIX"] & exception_message'
  missingPermissionMainCommand$: 'lut["MESSAGE_PREFIX"] & "&cYou don''t have the permission to use the main command."'
  missingPermissionLanguageCommand$: 'lut["MESSAGE_PREFIX"] & "&cYou don''t have the permission to use the language command."'
  missingPermissionFeatureSort$: 'lut["MESSAGE_PREFIX"] & "&cYou don''t have the permission to use sorting."'
  missingPermissionFeatureFilter$: 'lut["MESSAGE_PREFIX"] & "&cYou don''t have the permission to use filtering."'
  missingPermissionFeatureTeleport$: 'lut["MESSAGE_PREFIX"] & "&cYou don''t have the permission to use teleportation."'
  missingPermissionFeatureTeleportOtherWorld$: 'lut["MESSAGE_PREFIX"] & "&cYou don''t have the permission to teleport to other worlds."'
  missingPermissionReload$: 'lut["MESSAGE_PREFIX"] & "&cYou don''t have the permission to reload the plugin."'

predicates:
  mainLanguage: ENGLISH_US

commands:
  quickshopsearch:
    name: quickshopsearch
    aliases:
    - qss
  quickshopsearchlanguage:
    name: quickshopsearchlanguage
    aliases:
    - qssl
  quickshopsearchreload:
    name: quickshopsearchreload
    aliases:
    - qssrl

# File-global lookup table
lut:
  MESSAGE_PREFIX: '&7[&6QuickShopSearch&7] '
  textures:
    ARROW_LEFT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODU1MGI3Zjc0ZTllZDc2MzNhYTI3NGVhMzBjYzNkMmU4N2FiYjM2ZDRkMWY0Y2E2MDhjZDQ0NTkwY2NlMGIifX19'
    ARROW_LEFT_RED: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjg0ZjU5NzEzMWJiZTI1ZGMwNThhZjg4OGNiMjk4MzFmNzk1OTliYzY3Yzk1YzgwMjkyNWNlNGFmYmEzMzJmYyJ9fX0='
    ARROW_RIGHT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTYzMzlmZjJlNTM0MmJhMThiZGM0OGE5OWNjYTY1ZDEyM2NlNzgxZDg3ODI3MmY5ZDk2NGVhZDNiOGFkMzcwIn19fQ=='
    ARROW_RIGHT_RED: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmNmZTg4NDVhOGQ1ZTYzNWZiODc3MjhjY2M5Mzg5NWQ0MmI0ZmMyZTZhNTNmMWJhNzhjODQ1MjI1ODIyIn19fQ=='
  sortingCriteria:
    PRICE: 'Price'
    OWNER_NAME: 'Owner Name'
    STOCK_LEFT: 'Stock Left'
    SPACE_LEFT: 'Space Left'
    ITEM_TYPE: 'Item-Type'
    SHOP_TYPE: 'Shop-Type'
    DISTANCE: 'Distance'
  filteringCriteria:
    IS_BUYING: 'Buying'
    IS_SELLING: 'Selling'
    IS_UNLIMITED: 'Unlimited'
    HAS_STOCK_LEFT: 'Stock Left'
  sortingSelectionStyle:
    ASCENDING: '&a+ '
    DESCENDING: '&c- '
    INACTIVE: '&7/ &m'
  predicateSelectionStyle:
    POSITIVE: '&a'
    NEGATIVE: '&c'
    INVARIANT: '&7&m'