name: QuickShopSearch
main: me.blvckbytes.quick_shop_search.QuickShopSearchPlugin
version: 0.0.5
author: BlvckBytes
api-version: 1.13
depend: [QuickShop-Hikari, ItemPredicateParser]
commands:
  quickshopsearch:
    aliases: 'qss'
  quickshopsearchlanguage:
    aliases: 'qssl'
permissions:
  quickshopsearch.command.qss:
    description: 'Invoke the main command'
    default: op
  quickshopsearch.command.qssl:
    description: 'Invoke the language command'
    default: op
  quickshopsearch.empty-predicate:
    description: 'Query all shops without a predicate'
    default: op
  quickshopsearch.feature.sort:
    description: 'Use the sorting feature'
    default: op
  quickshopsearch.feature.filter:
    description: 'Use the filtering feature'
    default: op
  quickshopsearch.feature.teleport:
    description: 'Teleport to shops within the same world'
    default: op
  quickshopsearch.feature.teleport.other-world:
    description: 'Teleport to shops within another world'
    default: op