name: QuickShopSearch
main: me.blvckbytes.quick_shop_search.QuickShopSearchPlugin
version: 0.1
author: BlvckBytes
api-version: 1.21
depend: [QuickShop-Hikari, ItemPredicateParser]
commands:
  quickshopsearch:
    aliases: 'qss'
