name: QuickShopSearch
main: me.blvckbytes.quick_shop_search.QuickShopSearchPlugin
version: ${project.version}
author: BlvckBytes
api-version: 1.18
depend: [QuickShop-Hikari, ItemPredicateParser]
folia-supported: true
commands:
  quickshopsearch:
    description: 'Query shops using the main predicate language'
  quickshopsearchlanguage:
    description: 'Query shops using any supported predicate language'
  quickshopsearchreload:
    description: 'Reload the configuration-file'
permissions:
  quickshopsearch.command.qss:
    description: 'Invoke the main command'
    default: op
  quickshopsearch.command.qssl:
    description: 'Invoke the language command'
    default: op
  quickshopsearch.command.advertise:
    description: 'Invoke the advertise sub-command of QuickShop'
    default: op
  quickshopsearch.command.advertise.owner-bypass:
    description: 'Bypass having to be the owner of a shop to toggle advertising'
    default: op
  quickshopsearch.command.qssrl:
    description: 'Invoke the reload command'
    default: op
  quickshopsearch.empty-predicate:
    description: 'Query all shops without a predicate'
    default: op
  quickshopsearch.bypass-non-advertise:
    description: 'View non-advertising shops'
    default: op
  quickshopsearch.bypass-slow-teleport:
    description: 'Bypass having to wait for the teleportation-countdown'
    default: op
  quickshopsearch.bypass-access-lists:
    description: 'Bypass the permission-specific restrictions of access-lists'
    default: op
  quickshopsearch.other-world:
    description: 'Whether to display shops which are not in the same world as the player'
    default: op
  quickshopsearch.feature.sort:
    description: 'Use the sorting feature'
    default: op
  quickshopsearch.feature.filter:
    description: 'Use the filtering feature'
    default: op
  quickshopsearch.feature.teleport:
    description: 'Teleport to shops within the same world'
    default: op
  quickshopsearch.feature.teleport.bypass-cooldown.same-shop:
    description: 'Bypass the teleport cooldown for the same shop within the player''s world'
    default: op
  quickshopsearch.feature.teleport.bypass-cooldown.other-shop:
    description: 'Bypass the teleport cooldown for any shop within the player''s world'
    default: op
  quickshopsearch.feature.teleport.other-world:
    description: 'Teleport to shops within another world'
    default: op
  quickshopsearch.feature.teleport.other-world.bypass-cooldown.same-shop:
    description: 'Bypass the teleport cooldown for the same shop within a foreign world'
    default: op
  quickshopsearch.feature.teleport.other-world.bypass-cooldown.other-shop:
    description: 'Bypass the teleport cooldown for any shop within a foreign world'
    default: op
  quickshopsearch.feature.interact:
    description: 'Remotely interact with shops within the same world '
    default: op
  quickshopsearch.feature.interact.other-world:
    description: 'Remotely interact with shops within another world '
    default: op