# _______       _____      ______ _____________               ________                        ______
# __  __ \___  ____(_)________  /___  ___/__  /_________________  ___/__________ ________________  /_
# _  / / /  / / /_  /_  ___/_  //_/____ \__  __ \  __ \__  __ \____ \_  _ \  __ `/_  ___/  ___/_  __ \
# / /_/ // /_/ /_  / / /__ _  ,<  ____/ /_  / / / /_/ /_  /_/ /___/ //  __/ /_/ /_  /   / /__ _  / / /
# \___\_\\__,_/ /_/  \___/ /_/|_| /____/ /_/ /_/\____/_  .___//____/ \___/\__,_/ /_/    \___/ /_/ /_/
#                                                     /_/
#
# QuickShopSearch - Developed by BlvckBytes <blvckbytes@gmail.com>
# Repository - https://github.com/BlvckBytes/QuickShopSearch
# ASCII-Art - https://patorjk.com/software/taag/#p=display&f=Speed
#
# PRE-PROCESSOR-INPUT en_us.txt

# - current_page: Integer
# - number_pages: Integer
# - number_of_rows: Integer
# - last_slot: Integer
resultDisplay:
  title: '@{RESULT-DISPLAY-TITLE}'
  rows: 6
  paginationSlots$: 'range(0, 44)'
  items:
    # https://github.com/BlvckBytes/BukkitEvaluable#itemstack-section
    previousPage:
      slots$: 'last_slot - 8'
      type: PLAYER_HEAD
      textures$: 'lut["textures"][if current_page > 1 then "ARROW_LEFT" else "ARROW_LEFT_RED"]'
      name$: 'if current_page > 1 then @{PREVIOUS-PAGE-NAME-HAS} else @{PREVIOUS-PAGE-NAME-HAS-NOT}'
      lore$:
      - '" "'
      - '@{ANY-CONTROL-LORE-SPACER}'
      - '@{PREVIOUS-PAGE-LORE-LEFT-CLICK-DESCRIPTION}'
      - '@{PREVIOUS-PAGE-LORE-RIGHT-CLICK-DESCRIPTION}'
      - '@{ANY-CONTROL-LORE-SPACER}'
    # https://github.com/BlvckBytes/BukkitEvaluable#itemstack-section
    nextPage:
      slots$: 'last_slot'
      type: PLAYER_HEAD
      textures$: 'lut["textures"][if current_page < number_pages then "ARROW_RIGHT"
        else "ARROW_RIGHT_RED"]'
      name$: 'if current_page < number_pages then @{NEXT-PAGE-NAME-HAS} else @{NEXT-PAGE-NAME-HAS-NOT}'
      lore$:
      - '" "'
      - '@{ANY-CONTROL-LORE-SPACER}'
      - '@{NEXT-PAGE-LORE-LEFT-CLICK-DESCRIPTION}'
      - '@{NEXT-PAGE-LORE-RIGHT-CLICK-DESCRIPTION}'
      - '@{ANY-CONTROL-LORE-SPACER}'
    # - owner: String
    # - name: String?
    # - price: Double
    # - currency: String?
    # - remaining_stock: Integer
    # - remaining_space: Integer
    # - is_selling: Boolean
    # - is_buying: Boolean
    # - is_unlimited: Boolean
    # - loc_world: String
    # - loc_x: Integer
    # - loc_y: Integer
    # - loc_z: Integer
    # - distance: Integer
    # - can_teleport: Boolean
    # - can_interact: Boolean
    # https://github.com/BlvckBytes/BukkitEvaluable#itemstack-section
    representativePatch:
      lore$:
      - '" "'
      - '@{ANY-CONTROL-LORE-SPACER}'
      - '@{REPRESENTATIVE-LORE-OWNER}'
      - 'if name != null then @{REPRESENTATIVE-LORE-NAME} else null'
      - '@{REPRESENTATIVE-LORE-PRICE}'
      - |
        if is_buying then
          @{REPRESENTATIVE-LORE-REMAINING-SPACE(remaining_space=if is_unlimited then "∞" else remaining_space)}
        else
          @{REPRESENTATIVE-LORE-REMAINING-STOCK(remaining_stock=if is_unlimited then "∞" else remaining_stock)}
      - '@{REPRESENTATIVE-LORE-LOCATION-COORDINATES}'
      - '@{REPRESENTATIVE-LORE-LOCATION-WORLD}'
      - 'if distance < 0 then @{REPRESENTATIVE-LORE-DISTANCE-OTHER-WORLD} else @{REPRESENTATIVE-LORE-DISTANCE}'
      - |
        if is_buying then
          if is_unlimited then @{REPRESENTATIVE-LORE-MODE-BUYING-UNLIMITED} else @{REPRESENTATIVE-LORE-MODE-BUYING}
        else
          if is_unlimited then @{REPRESENTATIVE-LORE-MODE-SELLING-UNLIMITED} else @{REPRESENTATIVE-LORE-MODE-SELLING}
      - '@{ANY-CONTROL-LORE-SPACER}'
      - |
        if can_teleport then
          @{REPRESENTATIVE-LORE-LEFT-CLICK-DESCRIPTION}
        else
          null
      - '@{REPRESENTATIVE-LORE-RIGHT-CLICK-DESCRIPTION}'
      - |
        if can_interact then
          if is_buying then
             @{REPRESENTATIVE-LORE-SHIFT-LEFT-CLICK-BUYING-DESCRIPTION}
          else
             @{REPRESENTATIVE-LORE-SHIFT-LEFT-CLICK-SELLING-DESCRIPTION}
        else
          null
      - '@{ANY-CONTROL-LORE-SPACER}'
    # - sorting_selections: Iterable<SortingCriterionSelection>
    # - selected_index: Integer
    # - has_permission: Boolean
    # https://github.com/BlvckBytes/BukkitEvaluable#itemstack-section
    sorting:
      slots$: 'last_slot - 6'
      type: COMPARATOR
      name$: '@{SORTING-NAME}'
      lore$:
      - '" "'
      - |
        if not has_permission then
          @{SORTING-LORE-NO-PERMISSION}
        else
          flatten(
            @{ANY-CONTROL-LORE-SPACER},
            map(sorting_selections, (entry, entry_index) => (
              (if entry_index == selected_index then
                @{SORTING-LORE-ENTRY-PREFIX-ACTIVE}
              else
                @{SORTING-LORE-ENTRY-PREFIX-INACTIVE})
              & (lut["sortingSelectionStyle"][str(entry.selection)] ?? "&4?")
              & (lut["sortingCriteria"][str(entry.criterion)] ?? "&4?")
            )),
            @{ANY-CONTROL-LORE-SPACER},
            @{SORTING-LORE-LEFT-CLICK-DESCRIPTION},
            @{SORTING-LORE-RIGHT-CLICK-DESCRIPTION},
            @{SORTING-LORE-DROP-DESCRIPTION},
            @{SORTING-LORE-DROP-ALL-DESCRIPTION},
            @{ANY-CONTROL-LORE-SPACER}
          )
  # - filtering_selections: Map<ShopFilteringCriteria, PredicateSelection>
  # - selected_criteria: ShopFilteringCriteria
  # - has_permission: Boolean
  # https://github.com/BlvckBytes/BukkitEvaluable#itemstack-section
    filtering:
      slots$: 'last_slot - 2'
      type: HOPPER
      name$: '@{FILTERING-NAME}'
      lore$:
      - '" "'
      - |
        if not has_permission then
          @{FILTERING-LORE-NO-PERMISSION}
        else
          flatten(
            @{ANY-CONTROL-LORE-SPACER},
            map(filtering_selections, (entry) => (
              (if key(entry) == selected_criteria then
                @{FILTERING-LORE-ENTRY-PREFIX-ACTIVE}
              else
                @{FILTERING-LORE-ENTRY-PREFIX-INACTIVE})
              & (lut["filteringSelectionStyle"][str(value(entry))] ?? "&4?")
              & (lut["filteringCriteria"][str(key(entry))] ?? "&4?")
            )),
            @{ANY-CONTROL-LORE-SPACER},
            @{FILTERING-LORE-LEFT-CLICK-DESCRIPTION},
            @{FILTERING-LORE-RIGHT-CLICK-DESCRIPTION},
            @{FILTERING-LORE-DROP-ALL-DESCRIPTION},
            @{ANY-CONTROL-LORE-SPACER}
          )
  # https://github.com/BlvckBytes/BukkitEvaluable#itemstack-section
    filler:
      slots$:
        - 'last_slot - 7'
        - 'last_slot - 5'
        - 'last_slot - 4'
        - 'last_slot - 3'
        - 'last_slot - 1'
      type: BLACK_STAINED_GLASS_PANE
      name: " "

playerMessages:
  emptyPredicate$: '@{MESSAGE-EMPTY-PREDICATE(prefix=lut["MESSAGE_PREFIX"])}'
  noMatches$: '@{MESSAGE-NO-MATCHES(prefix=lut["MESSAGE_PREFIX"])}'
  # - owner: String
  # - name: String?
  # - price: Double
  # - currency: String?
  # - remaining_stock: Integer
  # - remaining_space: Integer
  # - is_selling: Boolean
  # - is_buying: Boolean
  # - is_unlimited: Boolean
  # - loc_world: String?
  # - loc_x: Integer
  # - loc_y: Integer
  # - loc_z: Integer
  # - distance: Integer
  beforeTeleporting$: '@{MESSAGE-BEFORE-TELEPORTING(prefix=lut["MESSAGE_PREFIX"])}'
  # - number_shops: Integer
  # - predicate: String
  beforeQuerying$: '@{MESSAGE-BEFORE-QUERYING(prefix=lut["MESSAGE_PREFIX"])}'
  # - number_shops: Integer
  queryingAllShops$: '@{MESSAGE-QUERYING-ALL-SHOPS(prefix=lut["MESSAGE_PREFIX"])}'
  # - label: String
  # - languages: Collection<String>
  usageQsslCommandLanguage$: |
    language_list = iter_cat(languages, (language) => @{MESSAGE-USAGE-QSSL-LANGUAGE-ITEM-COLOR} & language, @{MESSAGE-USAGE-QSSL-LANGUAGE-SEPARATOR-COLOR} & ", ")
    @{MESSAGE-USAGE-QSSL-LANGUAGE(prefix=lut["MESSAGE_PREFIX"])}
# - user_input: String
  unknownLanguageActionBar$: '@{MESSAGE-UNKNOWN-LANGUAGE(prefix=lut["MESSAGE_PREFIX"])}'
  pluginReloadedSuccess$: '@{MESSAGE-PLUGIN-RELOAD(prefix=lut["MESSAGE_PREFIX"])}'
  pluginReloadedError$: '@{MESSAGE-PLUGIN-RELOAD-ERROR(prefix=lut["MESSAGE_PREFIX"])}'
  # - error_message: String
  predicateParseError$: '@{MESSAGE-PREDICATE-ERROR(prefix=lut["MESSAGE_PREFIX"])}'
  shopInteractPromptBuying$: '@{MESSAGE-SHOP-INTERACT-PROMPT-BUYING(prefix=lut["MESSAGE_PREFIX"])}'
  shopInteractPromptSelling$: '@{MESSAGE-SHOP-INTERACT-PROMPT-SELLING(prefix=lut["MESSAGE_PREFIX"])}'
  shopInteractPromptTimeout$: '@{MESSAGE-SHOP-INTERACT-PROMPT-TIMEOUT(prefix=lut["MESSAGE_PREFIX"])}'
  shopInteractPromptDispatch$: '@{MESSAGE-SHOP-INTERACT-PROMPT-DISPATCH(prefix=lut["MESSAGE_PREFIX"])}'
  shopInteractPromptInvalidInput$: '@{MESSAGE-SHOP-INTERACT-PROMPT-INVALID-INPUT(prefix=lut["MESSAGE_PREFIX"])}'
  shopInteractPromptCancelPrevious$: '@{MESSAGE-SHOP-INTERACT-PROMPT-CANCEL-PREVIOUS(prefix=lut["MESSAGE_PREFIX"])}'
  shopInteractPromptCancelCurrent$: '@{MESSAGE-SHOP-INTERACT-PROMPT-CANCEL-CURRENT(prefix=lut["MESSAGE_PREFIX"])}'
  missingPermissionMainCommand$: '@{MESSAGE-MISSING-PERMISSION-MAIN-COMMAND(prefix=lut["MESSAGE_PREFIX"])}'
  missingPermissionLanguageCommand$: '@{MESSAGE-MISSING-PERMISSION-LANGUAGE-COMMAND(prefix=lut["MESSAGE_PREFIX"])}'
  missingPermissionReloadCommand$: '@{MESSAGE-MISSING-PERMISSION-RELOAD-COMMAND(prefix=lut["MESSAGE_PREFIX"])}'
  missingPermissionAdvertiseCommand$: '@{MESSAGE-MISSING-PERMISSION-ADVERTISE-COMMAND(prefix=lut["MESSAGE_PREFIX"])}'
  missingPermissionFeatureSort$: '@{MESSAGE-MISSING-PERMISSION-FEATURE-SORT(prefix=lut["MESSAGE_PREFIX"])}'
  missingPermissionFeatureFilter$: '@{MESSAGE-MISSING-PERMISSION-FEATURE-FILTER(prefix=lut["MESSAGE_PREFIX"])}'
  missingPermissionFeatureTeleport$: '@{MESSAGE-MISSING-PERMISSION-FEATURE-TELEPORT(prefix=lut["MESSAGE_PREFIX"])}'
  missingPermissionFeatureTeleportOtherWorld$: '@{MESSAGE-MISSING-PERMISSION-FEATURE-TELEPORT-OTHER-WORLD(prefix=lut["MESSAGE_PREFIX"])}'
  missingPermissionFeatureInteract$: '@{MESSAGE-MISSING-PERMISSION-FEATURE-INTERACT(prefix=lut["MESSAGE_PREFIX"])}'
  missingPermissionFeatureInteractOtherWorld$: '@{MESSAGE-MISSING-PERMISSION-FEATURE-INTERACT-OTHER-WORLD(prefix=lut["MESSAGE_PREFIX"])}'
  commandAdvertiseNotLookingAtShop$: '@{MESSAGE-ADVERTISE-NOT-LOOKING-AT-SHOP(prefix=lut["MESSAGE_PREFIX"])}'
  commandAdvertiseNotTheOwner$: '@{MESSAGE-ADVERTISE-NOT-THE-OWNER(prefix=lut["MESSAGE_PREFIX"])}'
  commandAdvertiseEnabledSelf$: '@{MESSAGE-ADVERTISE-ENABLED-SELF(prefix=lut["MESSAGE_PREFIX"])}'
  commandAdvertiseEnabledOther$: '@{MESSAGE-ADVERTISE-ENABLED-OTHER(prefix=lut["MESSAGE_PREFIX"])}'
  commandAdvertiseDisabledSelf$: '@{MESSAGE-ADVERTISE-DISABLED-SELF(prefix=lut["MESSAGE_PREFIX"])}'
  commandAdvertiseDisabledOther$: '@{MESSAGE-ADVERTISE-DISABLED-OTHER(prefix=lut["MESSAGE_PREFIX"])}'

predicates:
  mainLanguage: ENGLISH_US

shopAccessLists:

commands:
  quickShopSearch:
    name: quickshopsearch
    aliases:
    - qss
  quickShopSearchLanguage:
    name: quickshopsearchlanguage
    aliases:
    - qssl
  quickShopSearchAdvertise:
    name: quickshopsearchadvertise
    aliases:
      - qssa
  quickShopSearchReload:
    name: quickshopsearchreload
    aliases:
    - qssrl

# File-global lookup table
lut:
  MESSAGE_PREFIX: '@{MESSAGE-PREFIX}'
  textures:
    ARROW_LEFT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODU1MGI3Zjc0ZTllZDc2MzNhYTI3NGVhMzBjYzNkMmU4N2FiYjM2ZDRkMWY0Y2E2MDhjZDQ0NTkwY2NlMGIifX19'
    ARROW_LEFT_RED: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjg0ZjU5NzEzMWJiZTI1ZGMwNThhZjg4OGNiMjk4MzFmNzk1OTliYzY3Yzk1YzgwMjkyNWNlNGFmYmEzMzJmYyJ9fX0='
    ARROW_RIGHT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTYzMzlmZjJlNTM0MmJhMThiZGM0OGE5OWNjYTY1ZDEyM2NlNzgxZDg3ODI3MmY5ZDk2NGVhZDNiOGFkMzcwIn19fQ=='
    ARROW_RIGHT_RED: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmNmZTg4NDVhOGQ1ZTYzNWZiODc3MjhjY2M5Mzg5NWQ0MmI0ZmMyZTZhNTNmMWJhNzhjODQ1MjI1ODIyIn19fQ=='
  sortingCriteria:
    PRICE: '@{SORTING-LORE-CRITERIA-PRICE}'
    OWNER_NAME: '@{SORTING-LORE-CRITERIA-OWNER-NAME}'
    STOCK_LEFT: '@{SORTING-LORE-CRITERIA-STOCK-LEFT}'
    SPACE_LEFT: '@{SORTING-LORE-CRITERIA-SPACE-LEFT}'
    ITEM_TYPE: '@{SORTING-LORE-CRITERIA-ITEM-TYPE}'
    SHOP_TYPE: '@{SORTING-LORE-CRITERIA-SHOP-TYPE}'
    SHOP_NAME: '@{SORTING-LORE-CRITERIA-SHOP-NAME}'
    DISTANCE: '@{SORTING-LORE-CRITERIA-DISTANCE}'
    WORLD_NAME: '@{SORTING-LORE-CRITERIA-WORLD-NAME}'
  sortingSelectionStyle:
    ASCENDING: '@{SORTING-LORE-SELECTION-STYLE-ASCENDING}'
    DESCENDING: '@{SORTING-LORE-SELECTION-STYLE-DESCENDING}'
    INACTIVE: '@{SORTING-LORE-SELECTION-STYLE-INACTIVE}'
  filteringCriteria:
    IS_BUYING: '@{FILTERING-LORE-CRITERIA-IS-BUYING}'
    IS_SELLING: '@{FILTERING-LORE-CRITERIA-IS-SELLING}'
    IS_UNLIMITED: '@{FILTERING-LORE-CRITERIA-IS-UNLIMITED}'
    HAS_STOCK_LEFT: '@{FILTERING-LORE-CRITERIA-HAS-STOCK-LEFT}'
    HAS_SPACE_LEFT: '@{FILTERING-LORE-CRITERIA-HAS-SPACE-LEFT}'
    SAME_WORLD: '@{FILTERING-LORE-CRITERIA-SAME-WORLD}'
    CAN_BUY: '@{FILTERING-LORE-CRITERIA-CAN-BUY}'
  filteringSelectionStyle:
    POSITIVE: '@{FILTERING-LORE-SELECTION-STYLE-POSITIVE}'
    NEGATIVE: '@{FILTERING-LORE-SELECTION-STYLE-NEGATIVE}'
    INVARIANT: '@{FILTERING-LORE-SELECTION-STYLE-INVARIANT}'